
```{r}
library(data.table)
library(parallel)
source("../TADA-A/lib/TADA_Annotation.R")
```

Use coding window file. The previous scaling factors are still applicable. 

```{r, cache=TRUE}
prefix_vector <- data.frame(annotation_name = c("CADD",
                                                "CLIP",
                                                "CLIPdb",
                                                "CLIPdb_ribosnitch",
                                                "CLIP_ribosnitch",
                                                "GERP",
                                                "LoF",
                                                "Mis3",
                                                "Nonfunctional_syn",
                                                "ribosnitch",
                                                "spidex"), 
                            prefix = c("$1_CADD/$1_",
                                       "$1_CLIP/$1_CLIP_",
                                       "$1_CLIPdb/$1_CLIPdb_",
                                       "$1_CLIPdb_ribosnitch_",
                                       "$1_CLIP_ribosnitch_",
                                       "$1_GERP/$1_GERP_",
                                       "$1_LoF_",
                                       "$1_Mis3/$1_Mis3_",
                                       "$1_nonfunctional_syn/$1_nonfunctional_syn_",
                                       "$1_ribosnitch/$1_ribosnitch_",
                                       "$1_spidex/$1_spidex_"))

report_rr_from_compact_data_in_partitioned_form <- function(prefix_vector){
  report <- data.frame(annotation = NA, log_RR = NA, lower_bound = NA, upper_bound = NA)
  for(i in 1:length(prefix_vector[,1])){
    data_partition <- list()
    test = sprintf("%02d", 0:9)
    for(i in 1:10){
      temp <- readRDS(paste(prefix_vector[i,2], test[i], ".RDS", sep = ""))
      data_partition <- append(data_partition, temp$base_info)
    }
  temp <- TADA_A_RR_estimate(data = data_partition, selected_annotations = c(1), gene_prior_file = "../data/Example_gene_uniform_prior.txt", optimization_iteration = 2000, mode = \"single_fast\")
  print(temp)
  report[i,1] <- as.character(prefix_vector[i,1])
  report[i,2:4] <- temp$rr_report
  }
  return(report)
}

report <- report_rr_from_compact_data_in_partitioned_form(prefix_vector)
```

```{r}
knitr::kable(report)
```