---
output:
  html_document:
    toc: true
    number_sections: true
    theme: united
    highlight: textmate
---

```{r}
library(data.table)
library(parallel)
source("../TADA-A/lib/TADA_Annotation.R")

```



### Simulation 10 times
> with Log(nonfuonctional synonymous) = 0; Log(LoF) = 1.5, using Top 3000 genes, uniform prior
> Without including mutation rate adjustment

```{r}
nf_syn <- c()
LoF <- c()
```

```{r, cache=TRUE,cache.extra=TADA_A_DNM_generator}
set.seed(123)
for(i in 1 : 10){
TADA_A_DNM_generator(window_file = "../data/windows_partition/Example_windows_with_div_score_coding_00.with_header.txt",
                                 mutrate_scaling_files = c("../data/Example_windows_coding_with_nonfunctional_syn_mutrate_scaling_file_for_denovo_db_Iossifov_controls_DNM.txt"),
                                 sample_sizes = c(4000),
                                 gene_prior_file = "../data/Example_gene_uniform_prior.txt",
                                 nonAS_noncoding_annotations = NA,
                                 AS_noncoding_annotations = list(c("../other_annotations/coding/171029_synonymous_SNV_altA.bed.merge_removing_spidex_lower10pct.bed","../other_annotations/coding/171029_synonymous_SNV_altC.bed.merge_removing_spidex_lower10pct.bed","../other_annotations/coding/171029_synonymous_SNV_altG.bed.merge_removing_spidex_lower10pct.bed","../other_annotations/coding/171029_synonymous_SNV_altT.bed.merge_removing_spidex_lower10pct.bed"), c("../other_annotations/coding/171121_coding_stop_loss_and_gain_SNV_altA.bed.merge.bed","../other_annotations/coding/171121_coding_stop_loss_and_gain_SNV_altC.bed.merge.bed","../other_annotations/coding/171121_coding_stop_loss_and_gain_SNV_altG.bed.merge.bed","../other_annotations/coding/171121_coding_stop_loss_and_gain_SNV_altT.bed.merge.bed")),
                                 report_proportion = 18665/18665,
                                 chunk_partition_num =1 ,
                                 node_n = 1,
                                 mutrate_ref_files = c("../other_annotations/Mark_Daly_mutrate/Example_windows_extended_1bp_for_getting_base_level_mutrate.bed.fasta.tri.alt_A.mutrate.bw",
                      "../other_annotations/Mark_Daly_mutrate/Example_windows_extended_1bp_for_getting_base_level_mutrate.bed.fasta.tri.alt_C.mutrate.bw",
                      "../other_annotations/Mark_Daly_mutrate/Example_windows_extended_1bp_for_getting_base_level_mutrate.bed.fasta.tri.alt_G.mutrate.bw",
                      "../other_annotations/Mark_Daly_mutrate/Example_windows_extended_1bp_for_getting_base_level_mutrate.bed.fasta.tri.alt_T.mutrate.bw"),
                                 rr = c(0,2),
                                 output_allele_info_files = c("180301_LoF_1.5_nf_syn_0_for_mutrate_adjustment_with_allele_info.txt"),
                                 output_bed_files = c("180301_LoF_1.5_nf_syn_0_DNM_for_mutrate_adjustment.bed"),
                                 output_risk_genes_file = "180301_LoF_1.5_nf_syn_0_for_mutrate_adjustment_risk_genes.txt")
  
system("../external_tools/bedtools-2.17.0/bin/bedtools intersect -a 180301_LoF_1.5_nf_syn_0_DNM_for_mutrate_adjustment.bed -b ../other_annotations/coding/171029_synonymous_SNV_altA.bed.merge_removing_spidex_lower10pct.bed > 180301_LoF_1.5_nf_syn_0_DNM_for_mutrate_adjustment_nonfunctional_syn_Alt_A.bed")
system("../external_tools/bedtools-2.17.0/bin/bedtools intersect -a 180301_LoF_1.5_nf_syn_0_DNM_for_mutrate_adjustment.bed -b ../other_annotations/coding/171029_synonymous_SNV_altC.bed.merge_removing_spidex_lower10pct.bed > 180301_LoF_1.5_nf_syn_0_DNM_for_mutrate_adjustment_nonfunctional_syn_Alt_C.bed")
system("../external_tools/bedtools-2.17.0/bin/bedtools intersect -a 180301_LoF_1.5_nf_syn_0_DNM_for_mutrate_adjustment.bed -b ../other_annotations/coding/171029_synonymous_SNV_altG.bed.merge_removing_spidex_lower10pct.bed > 180301_LoF_1.5_nf_syn_0_DNM_for_mutrate_adjustment_nonfunctional_syn_Alt_G.bed")
system("../external_tools/bedtools-2.17.0/bin/bedtools intersect -a 180301_LoF_1.5_nf_syn_0_DNM_for_mutrate_adjustment.bed -b ../other_annotations/coding/171029_synonymous_SNV_altT.bed.merge_removing_spidex_lower10pct.bed > 180301_LoF_1.5_nf_syn_0_DNM_for_mutrate_adjustment_nonfunctional_syn_Alt_T.bed")

system("cat 180301_LoF_1.5_nf_syn_0_DNM_for_mutrate_adjustment_nonfunctional_syn_Alt_*.bed > 180301_LoF_1.5_nf_syn_0_DNM_for_mutrate_adjustment_nonfunctional_syn.bed")
  
  TADA_A_adjust_mutation_rate(mut_file = "180301_LoF_1.5_nf_syn_0_DNM_for_mutrate_adjustment_nonfunctional_syn.bed",
                            window_file = "../data/windows_partition/Example_windows_with_div_score_coding_nonfunctional_syn_mutrate_00.with_header.txt",
                            sample_size = 4000, 
                            scale_features = c("GC_content", "div_score"),
                            scaling_file_name = "180301_LoF_1.5_nf_syn_0_DNM_for_mutrate_adjustment_nonfunctional_scaling.txt",
                            mutrate_mode = "special")
  
  
  
  compact_data <- TADA_A_read_info(mut_files = c("180301_LoF_1.5_nf_syn_0_for_mutrate_adjustment_with_allele_info.txt"),
                                 window_file = "../data/windows_partition/Example_windows_with_div_score_coding_00.with_header.txt",
                                 mutrate_scaling_files = c("180301_LoF_1.5_nf_syn_0_DNM_for_mutrate_adjustment_nonfunctional_scaling.txt"),
                                 sample_sizes = c(4000),
                                 gene_prior_file = "../data/Example_gene_uniform_prior.txt",
                                 nonAS_noncoding_annotations = NA,
                                 AS_noncoding_annotations = list(c("../other_annotations/coding/171029_synonymous_SNV_altA.bed.merge_removing_spidex_lower10pct.bed","../other_annotations/coding/171029_synonymous_SNV_altC.bed.merge_removing_spidex_lower10pct.bed","../other_annotations/coding/171029_synonymous_SNV_altG.bed.merge_removing_spidex_lower10pct.bed","../other_annotations/coding/171029_synonymous_SNV_altT.bed.merge_removing_spidex_lower10pct.bed"), c("../other_annotations/coding/171121_coding_stop_loss_and_gain_SNV_altA.bed.merge.bed","../other_annotations/coding/171121_coding_stop_loss_and_gain_SNV_altC.bed.merge.bed","../other_annotations/coding/171121_coding_stop_loss_and_gain_SNV_altG.bed.merge.bed","../other_annotations/coding/171121_coding_stop_loss_and_gain_SNV_altT.bed.merge.bed")),
                                 report_proportion = 18665/18665,
                                 chunk_partition_num =1,
                                 node_n = 1,
                                 mutrate_ref_files = c("../other_annotations/Mark_Daly_mutrate/Example_windows_extended_1bp_for_getting_base_level_mutrate.bed.fasta.tri.alt_A.mutrate.bw",
                      "../other_annotations/Mark_Daly_mutrate/Example_windows_extended_1bp_for_getting_base_level_mutrate.bed.fasta.tri.alt_C.mutrate.bw",
                      "../other_annotations/Mark_Daly_mutrate/Example_windows_extended_1bp_for_getting_base_level_mutrate.bed.fasta.tri.alt_G.mutrate.bw",
                      "../other_annotations/Mark_Daly_mutrate/Example_windows_extended_1bp_for_getting_base_level_mutrate.bed.fasta.tri.alt_T.mutrate.bw")
)
 
nf_syn[i] <- TADA_A_RR_estimate(data = compact_data$base_info, selected_annotations = c(1), gene_prior_file = "../data/Example_gene_uniform_prior.txt", optimization_iteration = 2000)$mle$par
LoF[i] <- TADA_A_RR_estimate(data = compact_data$base_info, selected_annotations = c(2), gene_prior_file = "../data/Example_gene_uniform_prior.txt", optimization_iteration = 2000)$mle$par

system("rm 180301_LoF_1.5_nf_syn_0_with_allele_info.txt")
system("rm 180301_LoF_1.5_nf_syn_0_DNM.bed")
system("rm 180301_LoF_1.5_nf_syn_0_risk_genes.txt")
system("rm 180301_LoF_1.5_nf_syn_0_DNM_for_mutrate_adjustment_nonfunctional_scaling.txt")
}


```

```{r}
hist(nf_syn, main = "logRR distribution for nonfunctional syn")
hist(LoF, main = "logRR distribution for LoF")
```